version: '3'

services:
  instagram-bot:
    build: .
    restart: always
    volumes:
      - ./data:/app/data
      - ./credentials.json:/app/credentials.json
      - ./.env:/app/.env
    environment:
      - TZ=UTC
    # For interactive auth with Google (if needed)
    # ports:
    #   - "8080:8080"
