services:
  - type: web
    name: instagram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python render_webhook.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: GOOGLE_DRIVE_CREDENTIALS_BASE64
        sync: false
      - key: PORT
        value: "10000"
      - key: RENDER
        value: "true"
      - key: USE_GOOGLE_DRIVE
        value: "true"
    healthCheckPath: /
